<?php

namespace AppBundle\Repository;

/**
 * GasStationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GasStationRepository extends \Doctrine\ORM\EntityRepository
{
}
